# Generated by Django 4.2.6 on 2023-10-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('lifestyle', 'Lifestyle'), ('travel', 'Travel'), ('food', 'Food'), ('fashion', 'Fashion'), ('sports', 'Sports'), ('entertainment', 'Entertainment'), ('health', 'Health'), ('finance', 'Finance'), ('education', 'Education'), ('science', 'Science'), ('art', 'Art'), ('music', 'Music'), ('books', 'Books'), ('business', 'Business'), ('fitness', 'Fitness'), ('cooking', 'Cooking'), ('pets', 'Pets'), ('gaming', 'Gaming'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
