# Generated by Django 4.2.6 on 2023-10-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_alter_directory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='da',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='directory',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='directory',
            name='facebook_like',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='directory',
            name='image_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='directory',
            name='moz_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='directory',
            name='semrush_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='directory',
            name='title',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='directory',
            name='worth',
            field=models.FloatField(default=0),
        ),
    ]
