# Generated by Django 4.2.6 on 2023-10-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('da', models.IntegerField()),
                ('moz_rank', models.IntegerField()),
                ('semrush_rank', models.IntegerField()),
                ('facebook_like', models.FloatField()),
                ('worth', models.FloatField()),
                ('image_url', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
