# Generated by Django 4.2.6 on 2023-10-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_alter_directory_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
