# Generated by Django 4.2.6 on 2023-10-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_alter_directory_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
